import { SensorsData } from "../types";
import { getDiskData } from "./getDiscData";

const sensors = [
    "Date",
    "Time",
    "Virtual Memory Committed [MB]",
    "Virtual Memory Available [MB]",
    "Virtual Memory Load [%]",
    "Physical Memory Used [MB]",
    "Physical Memory Available [MB]",
    "Physical Memory Load [%]",
    "Page File Usage [%]",
    "Core VIDs (avg) [V]",
    "P-core 0 VID [V]",
    "P-core 1 VID [V]",
    "P-core 2 VID [V]",
    "P-core 3 VID [V]",
    "P-core 4 VID [V]",
    "P-core 5 VID [V]",
    "E-core 6 VID [V]",
    "E-core 7 VID [V]",
    "E-core 8 VID [V]",
    "E-core 9 VID [V]",
    "Uncore VID [V]",
    "SA VID [V]",
    "Core Clocks (avg) [MHz]",
    "P-core 0 Clock [MHz]",
    "P-core 1 Clock [MHz]",
    "P-core 2 Clock [MHz]",
    "P-core 3 Clock [MHz]",
    "P-core 4 Clock [MHz]",
    "P-core 5 Clock [MHz]",
    "E-core 6 Clock [MHz]",
    "E-core 7 Clock [MHz]",
    "E-core 8 Clock [MHz]",
    "E-core 9 Clock [MHz]",
    "Bus Clock [MHz]",
    "Ring/LLC Clock [MHz]",
    "Core Effective Clocks (avg) [MHz]",
    "P-core 0 T0 Effective Clock [MHz]",
    "P-core 0 T1 Effective Clock [MHz]",
    "P-core 1 T0 Effective Clock [MHz]",
    "P-core 1 T1 Effective Clock [MHz]",
    "P-core 2 T0 Effective Clock [MHz]",
    "P-core 2 T1 Effective Clock [MHz]",
    "P-core 3 T0 Effective Clock [MHz]",
    "P-core 3 T1 Effective Clock [MHz]",
    "P-core 4 T0 Effective Clock [MHz]",
    "P-core 4 T1 Effective Clock [MHz]",
    "P-core 5 T0 Effective Clock [MHz]",
    "P-core 5 T1 Effective Clock [MHz]",
    "E-core 6 T0 Effective Clock [MHz]",
    "E-core 7 T0 Effective Clock [MHz]",
    "E-core 8 T0 Effective Clock [MHz]",
    "E-core 9 T0 Effective Clock [MHz]",
    "Average Effective Clock [MHz]",
    "Core Usage (avg) [%]",
    "P-core 0 T0 Usage [%]",
    "P-core 0 T1 Usage [%]",
    "P-core 1 T0 Usage [%]",
    "P-core 1 T1 Usage [%]",
    "P-core 2 T0 Usage [%]",
    "P-core 2 T1 Usage [%]",
    "P-core 3 T0 Usage [%]",
    "P-core 3 T1 Usage [%]",
    "P-core 4 T0 Usage [%]",
    "P-core 4 T1 Usage [%]",
    "P-core 5 T0 Usage [%]",
    "P-core 5 T1 Usage [%]",
    "E-core 6 T0 Usage [%]",
    "E-core 7 T0 Usage [%]",
    "E-core 8 T0 Usage [%]",
    "E-core 9 T0 Usage [%]",
    "Max CPU/Thread Usage [%]",
    "Total CPU Usage [%]",
    "On-Demand Clock Modulation [%]",
    "Core Utility (avg) [%]",
    "P-core 0 T0 Utility [%]",
    "P-core 0 T1 Utility [%]",
    "P-core 1 T0 Utility [%]",
    "P-core 1 T1 Utility [%]",
    "P-core 2 T0 Utility [%]",
    "P-core 2 T1 Utility [%]",
    "P-core 3 T0 Utility [%]",
    "P-core 3 T1 Utility [%]",
    "P-core 4 T0 Utility [%]",
    "P-core 4 T1 Utility [%]",
    "P-core 5 T0 Utility [%]",
    "P-core 5 T1 Utility [%]",
    "E-core 6 T0 Utility [%]",
    "E-core 7 T0 Utility [%]",
    "E-core 8 T0 Utility [%]",
    "E-core 9 T0 Utility [%]",
    "Total CPU Utility [%]",
    "Core Ratios (avg) [x]",
    "P-core 0 Ratio [x]",
    "P-core 1 Ratio [x]",
    "P-core 2 Ratio [x]",
    "P-core 3 Ratio [x]",
    "P-core 4 Ratio [x]",
    "P-core 5 Ratio [x]",
    "E-core 6 Ratio [x]",
    "E-core 7 Ratio [x]",
    "E-core 8 Ratio [x]",
    "E-core 9 Ratio [x]",
    "Uncore Ratio [x]",
    "Core Temperatures (avg) [°C]",
    "P-core 0 [°C]",
    "P-core 1 [°C]",
    "P-core 2 [°C]",
    "P-core 3 [°C]",
    "P-core 4 [°C]",
    "P-core 5 [°C]",
    "E-core 6 [°C]",
    "E-core 7 [°C]",
    "E-core 8 [°C]",
    "E-core 9 [°C]",
    "Core Distance to TjMAX (avg) [°C]",
    "P-core 0 Distance to TjMAX [°C]",
    "P-core 1 Distance to TjMAX [°C]",
    "P-core 2 Distance to TjMAX [°C]",
    "P-core 3 Distance to TjMAX [°C]",
    "P-core 4 Distance to TjMAX [°C]",
    "P-core 5 Distance to TjMAX [°C]",
    "E-core 6 Distance to TjMAX [°C]",
    "E-core 7 Distance to TjMAX [°C]",
    "E-core 8 Distance to TjMAX [°C]",
    "E-core 9 Distance to TjMAX [°C]",
    "CPU Package [°C]",
    "Core Max [°C]",
    "Core Thermal Throttling (avg) [Yes/No]",
    "P-core 0 Thermal Throttling [Yes/No]",
    "P-core 1 Thermal Throttling [Yes/No]",
    "P-core 2 Thermal Throttling [Yes/No]",
    "P-core 3 Thermal Throttling [Yes/No]",
    "P-core 4 Thermal Throttling [Yes/No]",
    "P-core 5 Thermal Throttling [Yes/No]",
    "E-core 6 Thermal Throttling [Yes/No]",
    "E-core 7 Thermal Throttling [Yes/No]",
    "E-core 8 Thermal Throttling [Yes/No]",
    "E-core 9 Thermal Throttling [Yes/No]",
    "Core Critical Temperature (avg) [Yes/No]",
    "P-core 0 Critical Temperature [Yes/No]",
    "P-core 1 Critical Temperature [Yes/No]",
    "P-core 2 Critical Temperature [Yes/No]",
    "P-core 3 Critical Temperature [Yes/No]",
    "P-core 4 Critical Temperature [Yes/No]",
    "P-core 5 Critical Temperature [Yes/No]",
    "E-core 6 Critical Temperature [Yes/No]",
    "E-core 7 Critical Temperature [Yes/No]",
    "E-core 8 Critical Temperature [Yes/No]",
    "E-core 9 Critical Temperature [Yes/No]",
    "Core Power Limit Exceeded (avg) [Yes/No]",
    "P-core 0 Power Limit Exceeded [Yes/No]",
    "P-core 1 Power Limit Exceeded [Yes/No]",
    "P-core 2 Power Limit Exceeded [Yes/No]",
    "P-core 3 Power Limit Exceeded [Yes/No]",
    "P-core 4 Power Limit Exceeded [Yes/No]",
    "P-core 5 Power Limit Exceeded [Yes/No]",
    "E-core 6 Power Limit Exceeded [Yes/No]",
    "E-core 7 Power Limit Exceeded [Yes/No]",
    "E-core 8 Power Limit Exceeded [Yes/No]",
    "E-core 9 Power Limit Exceeded [Yes/No]",
    "Package/Ring Thermal Throttling [Yes/No]",
    "Package/Ring Critical Temperature [Yes/No]",
    "Package/Ring Power Limit Exceeded [Yes/No]",
    "CPU Package [°C]_2",
    "CPU IA Cores [°C]",
    "CPU GT Cores (Graphics) [°C]",
    "iGPU VID [V]_iGPU",
    "Voltage Offsets (avg) [V]",
    "IA Voltage Offset [V]",
    "GT Voltage Offset [V]",
    "CLR (CBo/LLC/Ring) Voltage Offset [V]",
    "GT Media Voltage Offset [V]",
    "SA Voltage Offset [V]",
    "L2 E-core Voltage Offset [V]",
    "VDDQ TX Voltage [V]",
    "VR VCC Current (SVID IOUT) [A]",
    "CPU Package Power [W]",
    "IA Cores Power [W]",
    "GT Cores Power [W]",
    "Total System Power [W]",
    "System Agent Power [W]",
    "Rest-of-Chip Power [W]",
    "PCH Power [W]",
    "PL1 Power Limit (Static) [W]",
    "PL1 Power Limit (Dynamic) [W]",
    "PL2 Power Limit (Static) [W]",
    "PL2 Power Limit (Dynamic) [W]",
    "GPU Clock [MHz]_iGPU",
    "GPU D3D Usage [%]_iGPU",
    "GPU D3D Utilizations (avg) [%]_iGPU",
    "GPU Video Decode 0 Usage [%]_iGPU",
    "GPU Video Processing 0 Usage [%]_iGPU",
    "GPU D3D Memory Dynamic [MB]_iGPU",
    "Current cTDP Level []",
    "Package C2 Residency [%]",
    "Core C0 Residency (avg) [%]",
    "P-core 0 T0 C0 Residency [%]",
    "P-core 0 T1 C0 Residency [%]",
    "P-core 1 T0 C0 Residency [%]",
    "P-core 1 T1 C0 Residency [%]",
    "P-core 2 T0 C0 Residency [%]",
    "P-core 2 T1 C0 Residency [%]",
    "P-core 3 T0 C0 Residency [%]",
    "P-core 3 T1 C0 Residency [%]",
    "P-core 4 T0 C0 Residency [%]",
    "P-core 4 T1 C0 Residency [%]",
    "P-core 5 T0 C0 Residency [%]",
    "P-core 5 T1 C0 Residency [%]",
    "E-core 6 T0 C0 Residency [%]",
    "E-core 7 T0 C0 Residency [%]",
    "E-core 8 T0 C0 Residency [%]",
    "E-core 9 T0 C0 Residency [%]",
    "Core C1 Residency (avg) [%]",
    "P-core 0 C1 Residency [%]",
    "P-core 1 C1 Residency [%]",
    "P-core 2 C1 Residency [%]",
    "P-core 3 C1 Residency [%]",
    "P-core 4 C1 Residency [%]",
    "P-core 5 C1 Residency [%]",
    "E-core 6 C1 Residency [%]",
    "E-core 7 C1 Residency [%]",
    "E-core 8 C1 Residency [%]",
    "E-core 9 C1 Residency [%]",
    "Core C6 Residency (avg) [%]",
    "P-core 0 C6 Residency [%]",
    "P-core 1 C6 Residency [%]",
    "P-core 2 C6 Residency [%]",
    "P-core 3 C6 Residency [%]",
    "P-core 4 C6 Residency [%]",
    "P-core 5 C6 Residency [%]",
    "E-core 6 C6 Residency [%]",
    "E-core 7 C6 Residency [%]",
    "E-core 8 C6 Residency [%]",
    "E-core 9 C6 Residency [%]",
    "Core C7 Residency (avg) [%]",
    "P-core 0 C7 Residency [%]",
    "P-core 1 C7 Residency [%]",
    "P-core 2 C7 Residency [%]",
    "P-core 3 C7 Residency [%]",
    "P-core 4 C7 Residency [%]",
    "P-core 5 C7 Residency [%]",
    "Memory Clock [MHz]",
    "Memory Clock Ratio [x]",
    "Tcas [T]",
    "Trcd [T]",
    "Trp [T]",
    "Tras [T]",
    "Trc [T]",
    "Trfc [T]",
    "Command Rate [T]",
    "Gear Mode []",
    "IA Limit Reasons (avg) [Yes/No]",
    "IA: PROCHOT [Yes/No]",
    "IA: Thermal Event [Yes/No]",
    "IA: Residency State Regulation [Yes/No]",
    "IA: Running Average Thermal Limit [Yes/No]",
    "IA: VR Thermal Alert [Yes/No]",
    "IA: VR TDC [Yes/No]",
    "IA: Electrical Design Point/Other (ICCmax,PL4,SVID,DDR RAPL) [Yes/No]",
    "IA: Package-Level RAPL/PBM PL1 [Yes/No]",
    "IA: Package-Level RAPL/PBM PL2,PL3 [Yes/No]",
    "IA: Max Turbo Limit [Yes/No]",
    "IA: Turbo Attenuation (MCT) [Yes/No]",
    "IA: Thermal Velocity Boost [Yes/No]",
    "GT Limit Reasons (avg) [Yes/No]",
    "GT: PROCHOT [Yes/No]",
    "GT: Thermal Event [Yes/No]",
    "GT: DDR RAPL [Yes/No]",
    "GT: Residency State Regulation [Yes/No]",
    "GT: Running Average Thermal Limit [Yes/No]",
    "GT: VR Thermal Alert [Yes/No]",
    "GT: VR TDC [Yes/No]",
    "GT: Max VR Voltage, ICCmax, PL4 [Yes/No]",
    "GT: Domain-Level PBM PLGT [Yes/No]",
    "GT: Package-Level RAPL/PBM PL1 [Yes/No]",
    "GT: Package-Level RAPL/PBM PL2,PL3 [Yes/No]",
    "GT: Inefficient Operation [Yes/No]",
    "GT: Fuses limit [Yes/No]",
    "Ring Limit Reasons (avg) [Yes/No]",
    "RING: PROCHOT [Yes/No]",
    "RING: Thermal Event [Yes/No]",
    "RING: DDR RAPL [Yes/No]",
    "RING: Residency State Regulation [Yes/No]",
    "RING: Running Average Thermal Limit [Yes/No]",
    "RING: VR Thermal Alert [Yes/No]",
    "RING: VR TDC [Yes/No]",
    "RING: Max VR Voltage, ICCmax, PL4 [Yes/No]",
    "RING: Package-Level RAPL/PBM PL1 [Yes/No]",
    "RING: Package-Level RAPL/PBM PL2,PL3 [Yes/No]",
    "PCH Temperature [°C]",
    "SPD Hub Temperature [°C]",
    "VDD (SWA) Voltage [V]",
    "VDDQ (SWB) Voltage [V]",
    "VPP (SWC) Voltage [V]",
    "1.8V VOUT Voltage [V]",
    "1.0V VOUT Voltage [V]",
    "VIN Voltage [V]",
    "PMIC High Temperature [Yes/No]",
    "PMIC Over Voltage [Yes/No]",
    "PMIC Under Voltage [Yes/No]",
    "Drive Temperature [°C]_1",
    "Drive Temperature 2 [°C]",
    "Drive Temperature 3 [°C]",
    "Drive Remaining Life [%]",
    "Drive Available Spare [%]",
    "Drive Failure [Yes/No]",
    "Drive Warning [Yes/No]",
    "Total Host Writes [GB]",
    "Total Host Reads [GB]",
    "Read Activity [%]",
    "Write Activity [%]",
    "Total Activity [%]",
    "Read Rate [MB/s]",
    "Write Rate [MB/s]",
    "Read Total [MB]",
    "Write Total [MB]",
    "GPU Temperature [°C]_dGPU",
    "GPU Memory Junction Temperature [°C]_dGPU",
    "GPU Thermal Limit [°C]_dGPU",
    "GPU Core Voltage [V]_dGPU",
    "GPU Rail Voltages (avg) [V]_dGPU",
    "GPU FBVDD Input Voltage [V]_dGPU",
    "GPU 12VHPWR Voltage [V]_dGPU",
    "GPU Power [W]_dGPU",
    "GPU Rail Powers (avg) [W]_dGPU",
    "GPU FBVDD Input Power [W]_dGPU",
    "GPU Core (NVVDD) Input Power (sum) [W]_dGPU",
    "GPU Misc0 Input Power (sum) [W]_dGPU",
    "GPU 12VHPWR Power [W]_dGPU",
    "GPU PCIe +3.3V Input Power (est) [W]_dGPU",
    "GPU Core (NVVDD) Output Power [W]_dGPU_1",
    "GPU Core (NVVDD) Output Power [W]_dGPU_2",
    "GPU Clock [MHz]_dGPU",
    "GPU Memory Clock [MHz]_dGPU",
    "GPU Video Clock [MHz]_dGPU",
    "GPU Effective Clock [MHz]_dGPU",
    "GPU Crossbar Clock [MHz]_dGPU",
    "GPU Core Load [%]_dGPU",
    "GPU Memory Controller Load [%]_dGPU",
    "GPU Video Engine Load [%]_dGPU",
    "GPU Bus Load [%]_dGPU",
    "GPU Memory Usage [%]_dGPU",
    "GPU D3D Usage [%]_dGPU",
    "GPU Video Decode 0 Usage [%]_dGPU",
    "GPU Video Encode 0 Usage [%]_dGPU",
    "GPU VR Usage [%]_dGPU",
    "Performance Limit - Power [Yes/No]_dGPU",
    "Performance Limit - Thermal [Yes/No]_dGPU",
    "Performance Limit - Reliability Voltage [Yes/No]_dGPU",
    "Performance Limit - Max Operating Voltage [Yes/No]_dGPU",
    "Performance Limit - Utilization [Yes/No]_dGPU",
    "Performance Limit - SLI GPUBoost Sync [Yes/No]_dGPU",
    "Receiver Errors []",
    "Replay Count []",
    "Replay Rollover Count []",
    "Bad DLLP Count []",
    "Bad TLP Count []",
    "LCRC Error Count []",
    "NAKs Sent Count []",
    "NAKs Received Count []",
    "Recovery Count []",
    "Correctable Error Count []",
    "Non-Fatal Error Count []",
    "Fatal Error Count []",
    "Unsupported Request Count []",
    "PCIe Lane 0 Errors []",
    "PCIe Lane 1 Errors []",
    "PCIe Lane 2 Errors []",
    "PCIe Lane 3 Errors []",
    "PCIe Lane 4 Errors []",
    "PCIe Lane 5 Errors []",
    "PCIe Lane 6 Errors []",
    "PCIe Lane 7 Errors []",
    "PCIe Lane 8 Errors []",
    "PCIe Lane 9 Errors []",
    "PCIe Lane 10 Errors []",
    "PCIe Lane 11 Errors []",
    "PCIe Lane 12 Errors []",
    "PCIe Lane 13 Errors []",
    "PCIe Lane 14 Errors []",
    "PCIe Lane 15 Errors []",
    "GPU Memory Available [MB]_dGPU",
    "GPU Memory Allocated [MB]_dGPU",
    "GPU D3D Memory Dedicated [MB]_dGPU",
    "GPU D3D Memory Dynamic [MB]_dGPU",
    "PCIe Link Speed [GT/s]",
    "Battery Voltage [V]",
    "Remaining Capacity [Wh]",
    "Charge Level [%]",
    "Charge Rate [W]",
    "Wear Level [%]",
    "Framerate Presented (avg) [FPS]",
    "Framerate Presented (99%) [FPS]",
    "Framerate Presented (1%) [FPS]",
    "Framerate Presented (0.1%) [FPS]",
    "Framerate Presented (1% low) [FPS]",
    "Framerate Presented (0.1% low) [FPS]",
    "Framerate Displayed (avg) [FPS]",
    "Framerate Displayed (99%) [FPS]",
    "Framerate Displayed (1%) [FPS]",
    "Framerate Displayed (0.1%) [FPS]",
    "Framerate Displayed (1% low) [FPS]",
    "Framerate Displayed (0.1% low) [FPS]",
    "Frame Time Presented (avg) [ms]",
    "Frame Time Presented (99%) [ms]",
    "Frame Time Presented (1%) [ms]",
    "Frame Time Presented (0.1%) [ms]",
    "Frame Time Displayed (1% high) [ms]",
    "Frame Time Displayed (0.1% high) [ms]",
    "GPU Busy (avg) [ms]_dGPU",
    "GPU Wait (avg) [ms]_dGPU",
    "CPU Busy (avg) [ms]",
    "CPU Wait (avg) [ms]",
    "Animation Error (avg) [ms]",
    "Total DL [MB]_1",
    "Total UP [MB]_1",
    "Current DL rate [KB/s]_interface1",
    "Current UP rate [KB/s]_interface1",
    "Total DL [MB]_2",
    "Total UP [MB]_2",
    "Current DL rate [KB/s]_interface2",
    "Current UP rate [KB/s]_interface2",
    "Total Errors []"
];
const cores = [
    "P-core 0 Clock [MHz]",
    "P-core 1 Clock [MHz]",
    "P-core 2 Clock [MHz]",
    "P-core 3 Clock [MHz]",
    "P-core 4 Clock [MHz]",
    "P-core 5 Clock [MHz]",
    "E-core 6 Clock [MHz]",
    "E-core 7 Clock [MHz]",
    "E-core 8 Clock [MHz]",
    "E-core 9 Clock [MHz]",
];


export const parseCsv = (rawData: string): SensorsData | null => {

    try {
        const discData = getDiskData();

        // Treating Data
        const values = rawData.split(",");

        // Verifiying if log is finished

        let sensorsData: SensorsData = {};

        values.forEach((value, index) => {
            sensorsData[sensors[index]] = value;
        });


        // calculating avearge clock
        let totalClock = 0;
        cores.forEach((core) => {
            totalClock += parseFloat(sensorsData[core].toString()) || 0;
        });

        const avgClock = totalClock / cores.length;

        sensorsData["Avearge Cpu Clock"] = avgClock;
        sensorsData = { ...sensorsData, ...discData };


        return sensorsData;
    }

    catch (err) {
        console.error("Error parsing CSV data:", err);
        return null;
    }

};


